# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

MY_P="${PN}-${PV}.tar"

DESCRIPTION="A simple library for writing soap web services"
HOMEPAGE="http://wiki.github.com/arskom/soaplib"
SRC_URI="http://github.com/downloads/arskom/soaplib/${MY_P}"
LICENSE="LGPL-2.1"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

