# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

# Warning: Invalid LICENSE.
inherit distutils


DESCRIPTION="An efficient paginator that works."
HOMEPAGE="http://github.com/dcramer/django-paging"
SRC_URI="http://pypi.python.org/packages/source/d/django-paging/${P}.tar.gz"
LICENSE="UNKNOWN"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/django-templatetag-sugar-0.1"

